MyGreatSite/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGreatSite.Domain;

namespace MyGreatSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.ProductsRepository.GetProducts());
        }
    }
}

MyGreatSite/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGreatSite.Domain;
using MyGreatSite.Models;

namespace MyGreatSite.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly DataManager dataManager;
        public ArticlesController(DataManager manager)
        {
            dataManager = manager;
        }

        public int PageSize = 4;
        public IActionResult Index(Guid id, int page = 1)
        {
            if (id != default)
                return View("Show", dataManager.ArticlesRepository.GetArticleById(id));
            ViewBag.TextField = dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageArticles");

            return View(new ListViewModel
            {
                Items = dataManager.ArticlesRepository.GetArticles()
                .OrderBy(a => a.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dataManager.ArticlesRepository.GetArticles().Count()
                }
            });
        }
    }
}

MyGreatSite/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyGreatSite.Domain;
using MyGreatSite.Domain.Entities;
using MyGreatSite.Models;
using MyGreatSite.Service;

namespace MyGreatSite.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly DataManager dataManager;
        public FeedbackController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public int PageSize = 4;
        public IActionResult Index(Guid id, int page = 1)
        {
            if (id != default)
                return View("Show", dataManager.FeedbackRepository.GetFeedbackById(id));
            ViewBag.TextField = dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageFeedback");
            return View(new ListViewModel
            {
                Items = dataManager.FeedbackRepository.GetAllFeedback()
                .OrderBy(a => a.Id)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = dataManager.ArticlesRepository.GetArticles().Count()
                }
            });
        }

        public IActionResult Write()
        {
            var entity = new Feedback();
            return View(entity);
        }

        [HttpPost]
        public IActionResult Write(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                dataManager.FeedbackRepository.SaveFeedback(feedback);
            }
            return RedirectToAction(nameof(FeedbackController.Index), nameof(FeedbackController).CutController());

        }
    }
}

MyGreatSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGreatSite.Domain;

namespace MyGreatSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageIndex"));
        }
        public IActionResult Contacts()
        {
            return View(dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageContacts"));
        }

        public IActionResult About()
        {
            return View(dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageAbout"));
        }

        public IActionResult Feedback()
        {
            return View(dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageFeedback"));
        }

        public IActionResult Articles()
        {
            return View(dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageArticles"));
        }
    }
}

MyGreatSite/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGreatSite.Domain.Entities;
using MyGreatSite.Domain.Repositories.Abstract;
using MyGreatSite.Models;
using MyGreatSite.Service;

namespace MyGreatSite.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult CheckOut() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else return View(order);
        }

        public IActionResult Cancel()
        {
            return RedirectToAction(nameof(CartController.Index), nameof(CartController).CutController());

        }
        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

MyGreatSite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyGreatSite.Domain;
using MyGreatSite.Models;

namespace MyGreatSite.Controllers
{
    public class ProductsController : Controller
    {
        private readonly DataManager dataManager;
        public ProductsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public int PageSize = 4;

        public IActionResult Index(Guid id, int productPage = 1)
        {
            if (id != default)
                return View("Show", dataManager.ProductsRepository.GetProductById(id));
            ViewBag.TextField = dataManager.TextFieldsRepository.GetTextFieldByCodeWord("PageProducts");
            return View(new ProductsListViewModel
            {
                Products = dataManager.ProductsRepository.GetProducts()
                        .OrderBy(p => p.Id)
                        .Skip((productPage - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = dataManager.ProductsRepository.GetProducts().Count()
                }
            });
        }
    }
}

MyGreatSite/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<Product>

@{
    string strTitle = "Страница администратора";
    ViewBag.Title = strTitle;
}

    <div>
        <h1>@strTitle</h1>
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-success">@TempData["Message"]</div>
            <script>
        alert(@TempData["Message"])
            </script>
        }

        <div class="div-box">
            <h3>Редактировать страницы сайта</h3>
            <div>
                <ul>
                    <li>
                        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageProducts">Наши товары</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageAbout">Обо мне</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageArticles">Статьи</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageFeedback">Отзывы</a>
                    </li>
                </ul>
            </div>
        </div>

        <div>
            <ul>
                <li>
                    <a asp-area="Admin" asp-controller="Order" asp-action="Index" asp-route-id="">Управление заказами</a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Articles" asp-action="Index" asp-route-id="">Добавить/Редактировать статьи</a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Feedback" asp-action="Index" asp-route-id="">Добавить/Редактировать отзывы</a>
                </li>
            </ul>
        </div>

        <div class="div-box">
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
                <input type="submit" value="Выйти" />
            </form>
        </div>

        <div>
            <h4>Наши товары</h4>
            <div>
                <a asp-area="Admin" asp-controller="Products" asp-action="Edit" asp-route-id="" class="button">Добавить товар</a>
            </div>
            <br />
            <div>
                @if (Model.Any())
                {
                    <div class="row">
                        @foreach (var p in Model)
                        {
                            <div class="col-6 col-12-large">
                                <h3>@p.Title</h3>
                                <p>@p.Subtitle</p>

                                <ul class="actions">
                                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Edit" asp-route-id="@p.Id" class="button big">Редактировать</a></li>
                                    <li>
                                        <form style="display: inline-block;" id="form-@p.Id" asp-area="Admin" asp-controller="Products" asp-action="Delete" method="post">
                                            <input type="hidden" name="id" value="@p.Id" />
                                            <a href="#" onclick="document.getElementById('form-@p.Id').submit();" class="button big">удалить</a>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                            <div сlass="col-4 col-12-small">
                                <img class="img-block" src="~/images/@p.TitleImagePath" />
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>